services:
  # ==============================
  # HADOOP HDFS & YARN
  # ==============================
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    environment:
      - CLUSTER_NAME=test-cluster
      - HDFS_CONF_dfs_hosts_exclude=/etc/hadoop/dashboard/excluded-datanodes
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./dashboard/state:/etc/hadoop/dashboard:ro
    networks:
      - bigdata-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    depends_on:
      - namenode
    ports:
      - "9864:9864"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - bigdata-net

  datanode-2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-2
    hostname: datanode-2
    profiles: [extra-datanodes]
    restart: always
    depends_on:
      - namenode
    ports:
      - "9865:9864"
    environment:
      - HDFS_CONF_dfs_datanode_hostname=datanode-2
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode_2:/hadoop/dfs/data
    networks:
      - bigdata-net

  datanode-3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode-3
    hostname: datanode-3
    profiles: [extra-datanodes]
    restart: always
    depends_on:
      - namenode
    ports:
      - "9867:9864"
    environment:
      - HDFS_CONF_dfs_datanode_hostname=datanode-3
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_datanode_3:/hadoop/dfs/data
    networks:
      - bigdata-net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    depends_on:
      - namenode
      - datanode
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    depends_on:
      - namenode
      - datanode
      - resourcemanager
    ports:
      - "8042:8042"
    env_file:
      - ./hadoop.env
    networks:
      - bigdata-net


volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_datanode_2:
  hadoop_datanode_3:

networks:
  bigdata-net:
    driver: bridge
